subjects = [10,20,30,40,50]
"""
print(subjects[1])
print(subjects[2:])
print(subjects[:-1])
print(subjects+["Swift",23])
print("SQL" in subjects)
print("SQL" not in subjects)
"""
print(len(subjects))
subjects.append(60)
print(subjects)
subjects.insert(1,70)
print(subjects)
subjects.remove(70)
print(subjects)
subjects.sort()
print(subjects)
subjects.reverse()
print(subjects)
subjects.pop()
print(subjects)
#subjects.pop()
#print(subjects)
#subjects.clear()
#print(subjects)
subjects2 = subjects.copy()
print(subjects2)
pos1 = subjects.index(20)
print(pos1)
pos = subjects.count(40)
print(pos)